import attractionMarkerImage from "./assets/images/attraction-marker.png";
import activityMarkerImage from "./assets/images/activity-marker.png";

export const attractionMarkerIcon = L.icon({
  iconUrl: attractionMarkerImage,
  iconSize: [40, 40],
  iconAnchor: [16, 32],
});

export const activityMarkerIcon = L.icon({
  iconUrl: activityMarkerImage,
  iconSize: [40, 40],
  iconAnchor: [16, 32],
});

const DUMMY_ACTIVITY_API_DATA = {
  context: "http://schema.org",
  type: [
    "LocalBusiness",
    "TouristAttraction",
    "LandmarksOrHistoricalBuildings",
  ],
  address: {
    type: "PostalAddress",
    addressLocality: "Conna",
    addressRegion: "Cork",
    addressCountry: "Republic of Ireland",
  },
  geo: {
    type: "GeoCoordinates",
    longitude: -8.1016545,
    latitude: 52.0945205,
  },
  image: {
    type: "ImageObject",
    caption: "Fáilte Ireland Logo",
    url: "https://failtecdn.azureedge.net/failteireland/F%C3%A1ilte_Ireland_Logo_OpenDataAPI.jpg",
  },
  name: "Conna Castle",
  tags: ["Activity", "Castle", "Attraction", "Historic Houses and Castle"],
  telephone: "+353862149601",
  url: "https://www.castles.nl/conna-castle",
};

export const ALL_TAGS = [
  "Food and Drink",
  "Restaurant",
  "Local Produce",
  "Kayaking",
  "Activity Operator",
  "Walking",
  "Day Tour",
  "Tour",
  "Boat",
  "Traditionally Irish",
  "Venue",
  "Music",
  "Forest Park",
  "Park and Forest Walk",
  "Cycling",
  "Public Park",
  "Nature and Wildlife",
  "Bird Watching",
  "Craft",
  "Shopping",
  "Shopping Centres and Department Store",
  "Food Shops",
  "Cafe",
  "Tracing Your Ancestors",
  "Transport",
  "Horse Riding",
  "Equestrian",
  "Coach",
  "Road",
  "Pubs and Bar",
  "Movies",
  "Cinema",
  "Pampering",
  "Health Farm",
  "Spa and Wellness",
  "Specialised Retreat",
  "Fitness and Leisure",
  "Fast Food",
  "Cruising",
  "Bike Rental",
  "Fishing",
  "Angling",
  "Comedy",
  "Swimming",
  "Swimming Pools and Water Park",
  "Swimming Pool",
  "Sailing",
  "Cooking",
  "Cookery",
  "Learning",
  "Climbing",
  "Golf",
  "Zip Lining",
  "Marina",
  "Vegetarian",
  "Seafood",
  "Photography",
  "Sports Venues",
  "Adventure Park",
  "Spa",
  "Agriculture",
  "Kitesurfing",
  "Windsurfing",
  "Surfing",
  "Artisan",
  "Food Trails and Tour",
  "Race Course",
  "Fine Dining",
  "Vegan",
  "Golf Course",
  "Gardening",
  "Historic Houses and Castle",
  "Island",
  "Offshore Island",
  "Natural Landscape",
  "Art Gallery",
  "Museums and Attraction",
  "Castle",
  "Visitor Farm",
  "Church Abbey",
  "Monastery",
  "Churches",
  "Abbeys and Monastery",
  "Falconry",
  "Gardens",
  "Garden",
  "Embarkation Point",
  "River",
  "Discovery Point",
  "Ruins",
  "Literary Ireland",
  "Zoos and Aquarium",
  "Public Sculpture",
  "National Park",
  "National and Forest Park",
  "Driving Range",
  "General",
  "Golf Driving Range",
  "Gaa",
  "Pitch And Putt",
  "Pitch and Putt",
  "Beach",
  "Banquet",
  "Casinos",
  "Stadium",
  "Sports Venue",
];
